# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "JmeterRun"
  JmeterRun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.282'
          java-package: jdk
          architecture: x64
      - name: check JAVA version
        run:
          java -version
      - name: install dependency
        run: |
          sudo apt-get update
          sudo apt install curl -y
      - name: install jmeter
        env:
          JMETER_VERSION: 5.5    
        run: |
          mkdir jm55
          cd jm55/
          curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xvf apache-jmeter-$JMETER_VERSION.tgz 
          echo "jmeter.save.saveservice.output_format=csv" >> /tmp/apache-jmeter-$JMETER_VERSION/bin/jmeter.properties
          echo "jmeter.save.saveservice.response_data.on_error=true" >> /tmp/apache-jmeter-$JMETER_VERSION/bin/jmeter.properties
          rm -rf apache-jmeter-$JMETER_VERSION/docs apache-jmeter-$JMETER_VERSION/printable_docs 
          cd apache-jmeter-$JMETER_VERSION/lib
          curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
          
          cd ext/
          curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.8/jmeter-plugins-manager-1.8.jar
          cd ..
          java  -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-graphs-basic, jpgc-cmd

          ln -s /jm55/apache-jmeter-$JMETER_VERSION /opt/jmeter 
          mkdir -p -m 777 /home/runner/work/QA_Auto_PerformanceTesting/QA_Auto_PerformanceTesting/jmeter_report/PerfTestReport
          mkdir -p -m 777 /home/runner/work/QA_Auto_PerformanceTesting/QA_Auto_PerformanceTesting/jmeter_report/jmeter_logs
          
      - name: run jmeter
        run: |
          /opt/jmeter/bin/jmeter.sh \
          -n \
          -t JMeterFiles/PF_FullTestSuite.jmx \
          -l jmeter_report/jmeter_logs/pf.jtl \
          -j jmeter_report/jmeter_logs/pf.log \
          -e \
          -o jmeter_report/PerfTestReport
          /opt/jmeter/bin/JMeterPluginsCMD.bat --generate-png response.png --input-jtl jmeter_report/jmeter_logs/pf.jtl --plugin-type ResponseTimesOverTime --width 800 --height 600 
      
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: PerfTestReport
          path: /home/runner/work/QA_Auto_PerformanceTesting/QA_Auto_PerformanceTesting/jmeter_report 
          
          
          
          
