# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "JmeterRun"
  JmeterRun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v3        #checkout jmeter project source files.
      - name: where are the files?
        run: |
           pwd
           ls
           cd JmeterFiles/
           ls
      - uses: actions/setup-java@v1      #install java environment
        with:
          java-version: '8.0.282'
          java-package: jdk
          architecture: x64
      - name: check JAVA version
        run:
          java -version
      - name: install dependency         # install curl, for download jmeter plugins
        run: |
          sudo apt-get update
          sudo apt install curl -y
      - name: install jmeter
        env:
          JMETER_VERSION: 5.5    
        run: |
          # mkdir jm55
          # cd jm55/
          curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
          tar -xvf apache-jmeter-$JMETER_VERSION.tgz 
          echo "jmeter.save.saveservice.output_format=csv" >> apache-jmeter-$JMETER_VERSION/bin/jmeter.properties
          echo "jmeter.save.saveservice.response_data.on_error=true" >> apache-jmeter-$JMETER_VERSION/bin/jmeter.properties
          rm -rf apache-jmeter-$JMETER_VERSION/docs apache-jmeter-$JMETER_VERSION/printable_docs 
          cd apache-jmeter-$JMETER_VERSION/bin
          ./jmeter -v
          pwd
          
      - name: install plugins
        env:
          JMETER_VERSION: 5.5           
        run: |  
          cd $GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/lib
          curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar   
          pwd
          ls
          cd ext/
          # install jmeter plugin manager
          curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.8/jmeter-plugins-manager-1.8.jar
          cd ..
          # install plugins:  jpgc-graphs-basic,jpgc-cmd
          # jpgc-graphs-basic is required to run jpgc-cmd
          # for other plugins:  https://jmeter-plugins.org/ ,  https://jmeter-plugins.org/files/packages/
          java  -jar cmdrunner-2.2.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-graphs-basic,jpgc-cmd

          cd $GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/lib
          #cmdrunner-2.2.jar disappeared after installing the plugin, not sure why. So downlaod again
          curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar  
          pwd
          ls
          cd $GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/lib/ext
          pwd
          ls
          mkdir -p -m 777 $GITHUB_WORKSPACE/jmeter_report/PerfTestReport
          mkdir -p -m 777 $GITHUB_WORKSPACE/jmeter_report/jmeter_logs
          pwd

        
      - name: run jmeter
        env:
          JMETER_VERSION: 5.5   
        run: |
          # /opt/apache-jmeter-$JMETER_VERSION/bin/jmeter.sh \
          pwd
          $GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/bin/jmeter.sh \
          -n \
          -t JmeterFiles/PF_FullTestSuite.jmx \
          -l jmeter_report/jmeter_logs/pf.jtl \
          -j jmeter_report/jmeter_logs/pf.log \
          -e \
          -o jmeter_report/PerfTestReport
          cd jmeter_report/jmeter_logs/
          pwd
          ls
          # run JMeterPluginsCMD to generate pictures
          $GITHUB_WORKSPACE/apache-jmeter-$JMETER_VERSION/bin/JMeterPluginsCMD.sh --generate-png $GITHUB_WORKSPACE/jmeter_report/jmeter_logs/response.png --input-jtl $GITHUB_WORKSPACE/jmeter_report/jmeter_logs/pf.jtl --plugin-type ResponseTimesOverTime --width 800 --height 600 
      
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: PerfTestReport
          path: /home/runner/work/KirstenLearning1/KirstenLearning1/jmeter_report/ 
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:    
          server_address: ${{ secrets.SMTPSERVERHOST }}
          server_port: ${{ secrets.SMTPSERVERPORT }}
          username: ${{secrets.MAILUSERNAME}}
          password: ${{secrets.MAILPASSWORD}}
          subject: Kirsten Test
          to: chongle.chen@osim.com.sg
          from: GitHub Actions
          attachments: /home/runner/work/KirstenLearning1/KirstenLearning1/jmeter_report/jmeter_logs/response.png     
          
          
          
